policy:
  approvers:
    HIGH: ["ai-security-approvers"]
    MED: []
    LOW: []
  eval_suites:
    HIGH: ["smoke", "regression"]
    MED: ["smoke"]
    LOW: []
override:
  allowed: true
  ttl_hours: 12
